name: FFTW ARMv7 Build

on:
  push:
  pull_request:

jobs:
  build-armv7:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Make build scripts executable
        run: chmod +x scripts/*.sh

      - name: Install cross-compile tools and QEMU
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc-arm-linux-gnueabi g++-arm-linux-gnueabi \
            gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf \
            gcc-aarch64-linux-gnu g++-aarch64-linux-gnu \
            wget make \
            qemu-user qemu-user-static

      - name: Verify qemu-arm installation
        run: qemu-arm --version

      - name: Copy fftw_bench.c to scripts
        run: cp fftw_bench.c scripts/

      - name: Build ARMv7-A (hard float)
        run: echo "1" | scripts/fftw_build_armv7a_soft_hard.sh

      - name: Build ARMv7-A (soft float)
        run: echo "2" | scripts/fftw_build_armv7a_soft_hard.sh

      - name: List files in bin
        run: ls -la bin/

      - name: Run ARMv7 hard float binary in QEMU
        run: |
          qemu-arm -L /usr/arm-linux-gnueabihf bin/fftw_bench_armv7a_hard_float > bin/qemu_bench_hard.log 2>&1 || echo "QEMU returned error, but continuing"

      - name: Run ARMv7 soft float binary in QEMU
        run: |
          qemu-arm -L /usr/arm-linux-gnueabi bin/fftw_bench_armv7a_soft_float > bin/qemu_bench_soft.log 2>&1 || echo "QEMU returned error, but continuing"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fftw-binaries
          path: bin/fftw_bench_*

      - name: Upload QEMU logs
        uses: actions/upload-artifact@v4
        with:
          name: qemu-benchmark-logs
          path: bin/qemu_bench_*.log
